# Generated by Django 5.2.3 on 2025-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], default='cod', max_length=20),
        ),
    ]
